### ISSUE TITLE
Test QC1d ontbreekt maar wordt impliciet uitgevoerd

### ISSUE THREAD

**Issue by jspijker** [jspijker/KRWQCprotocol#6]
De QC1d test controleerd of alle kolommen in de data aanwezig zijn die nodig zijn voor de tests. In het QC protocol is dit een aparte check, maar in het pakket is dit onderdeel van standaard tests die voor iedere functie uitgevoerd worden (zie R/QCvalidate-helpers.R).

Het ontbreken van QC1d moet even opgenomen worden in de vignette

**Comment by gilsvda** [comment]
Het ontbreken van QC1d is al opgenomen in de vignette onder de kop QC1
